// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CompanyEmployee.Migrations
{
    [DbContext(typeof(RepositoryContest))]
    partial class RepositoryContestModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("838ddb33-9e6a-48e5-a63f-286e46947bd4"),
                            Address = "Dhaka, Bangladesh",
                            Country = "Bangladesh",
                            Name = "IT Solution Ltd"
                        },
                        new
                        {
                            Id = new Guid("b42606ee-bc60-49de-bbaf-9eb38cbd419c"),
                            Address = "321 Forest Avenue, BF 923",
                            Country = "USA",
                            Name = "Admin Solutions Ltd"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("025cd8ff-04aa-4a36-8c95-f69376f842a7"),
                            Age = 26,
                            CompanyId = new Guid("838ddb33-9e6a-48e5-a63f-286e46947bd4"),
                            Name = "Sam Raiden",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("8c0ba96a-e0fd-4136-988d-de204a6d889b"),
                            Age = 27,
                            CompanyId = new Guid("838ddb33-9e6a-48e5-a63f-286e46947bd4"),
                            Name = "Jana McLeaf",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("a4aef1ef-7fec-42d0-9ec0-6d25bd1d05b5"),
                            Age = 28,
                            CompanyId = new Guid("b42606ee-bc60-49de-bbaf-9eb38cbd419c"),
                            Name = "Kane Miller",
                            Position = "Administrator"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
